k8sServiceHost: "PLACEHOLDER_SANDBOX_CP_IP"
k8sServicePort: 6443
kubeProxyReplacement: true
operator:
  replicas: 1
ipam:
  mode: kubernetes
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: false
l2announcements:
  enabled: true
gatewayAPI:
  enabled: true
