tunnelSecrets:
    existingPemFileSecret:
        name: "tunnel-cert" # 1단계에서 생성한 Secret의 이름
        # 'cert.pem'이 아닌 1단계에서 지정한 키 이름으로 설정
        key: "origin.pem"
    existingConfigJsonFileSecret:
        name: "tunnel-credentials"
        key: "credentials.json"
tunnelConfig:
    name: "eecs-playbox-k8s"

ingress:
    - hostname: "auth.jinwang.dev"
      service: "http://keycloak.default:80"
      originRequest:
          noHappyEyeballs: true
          http2Origin: false
    - hostname: "k8s.jinwang.dev"
      service: "https://kubernetes.default.svc:443"
      originRequest:
          noTLSVerify: true
    - service: "http_status:404"