tunnelSecrets:
  existingConfigJsonFileSecret:
    name: cloudflared-tunnel-credentials
    key: credentials.json
tunnelConfig:
  name: "playbox-admin-static"
ingress:
  - hostname: "api.k8s.jinwang.dev"
    service: "https://kubernetes.default.svc:443"
    originRequest:
      noTLSVerify: true
  - hostname: "auth.jinwang.dev"
    service: "http://keycloak.keycloak.svc.cluster.local:80"
  - hostname: "cd.jinwang.dev"
    service: "http://argocd-server.argocd.svc.cluster.local:8080"
  - service: "http_status:404"
