# See https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html

[all]
playbox-0  ansible_host=192.168.88.8   ip=192.168.88.8
playbox-1  ansible_host=192.168.88.9   ip=192.168.88.9
playbox-2  ansible_host=192.168.88.10  ip=192.168.88.10
playbox-3  ansible_host=192.168.88.11  ip=192.168.88.11


[kube_control_plane]
playbox-0

[etcd:children]
kube_control_plane

[worker_nodes]
playbox-1
playbox-2
playbox-3

[kube_node:children]
worker_nodes

[k8s_cluster:children]
kube_control_plane
kube_node

[gpu_nodes]
playbox-3

# ------------------------------------------------------------
[worker_nodes:vars]
_worker_group_labels = {'node_group': 'worker_node'}

[gpu_nodes:vars]
_gpu_group_labels = {'gpu_node': 'true'}

[kube_node:vars]
node_labels="{{ _worker_group_labels | default({}) | combine(_gpu_group_labels | default({})) }}"