apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: playbox-ingress-ip-pool
spec:
  blocks:
    - cidr: "192.168.88.32/27"  # 32 ~ 63 (32개)
    - cidr: "192.168.88.64/27"  # 64 ~ 95 (32개)
    - cidr: "192.168.88.96/30"  # 96 ~ 99 (4개)
    - cidr: "192.168.88.100/32" # 100 (1개)