# Common apps deployed to Sandbox cluster (remote)
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sandbox-common
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - appName: cilium-resources
            namespace: kube-system
            syncWave: "2"
          - appName: cert-manager
            namespace: cert-manager
            syncWave: "1"
          - appName: kyverno
            namespace: kyverno
            syncWave: "1"
          - appName: kyverno-policies
            namespace: kyverno
            syncWave: "2"
          - appName: scalex-dash-rbac
            namespace: scalex-system
            syncWave: "4"
  template:
    metadata:
      name: "sandbox-{{.appName}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{.syncWave}}"
    spec:
      project: sandbox-project
      source:
        repoURL: https://github.com/JinwangMok/ScaleX-POD-mini.git
        targetRevision: main
        path: "gitops/common/{{.appName}}"
      destination:
        name: sandbox
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
