# You should manually add before deploy Keycloak like
# kubectl create secret generic keycloak-db-secret -n keycloak \
#   --from-literal=username=REDACTED_USER \
#   --from-literal=password=REDACTED_PASS
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-pgsql-db
  namespace: keycloak
spec:
  serviceName: keycloak-pgsql-db-service
  selector:
    matchLabels:
      app: keycloak-pgsql-db
  replicas: 1
  volumeClaimTemplates:
    - metadata:
        name: cache-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "dx-ceph-standard-block"
        resources:
          requests:
            storage: 10Gi
  template:
    metadata:
      labels:
        app: keycloak-pgsql-db
    spec:
      containers:
        - name: keycloak-pgsql-db
          image: postgres:15
          volumeMounts:
            - mountPath: /data
              name: cache-volume
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: password
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRES_DB
              value: keycloak
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-pg
  namespace: keycloak
spec:
  selector:
    app: keycloak-pgsql-db
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
