tunnelSecrets:
    existingPemFileSecret:
        name: "tunnel-cert" # 1단계에서 생성한 Secret의 이름
        key: "origin.pem"   # 'cert.pem'이 아닌 1단계에서 지정한 키 이름으로 설정
    existingConfigJsonFileSecret:
        name: "tunnel-credentials"
        key: "credentials.json"
tunnelConfig:
    name: "playbox-admin-static"
ingress:
    - hostname: "api.k8s.jinwang.dev"
      service: "tcp://socks5-proxy.kube-system:1080"
    #   originRequest:
    #       noTLSVerify: true    
    
    - hostname: "auth.jinwang.dev"
      service: "http://cilium-gateway-playbox-external-gateway.playbox-service.svc.cluster.local:80"
    
    - hostname: "dashboard.k8s.jinwang.dev"
      service: "http://cilium-gateway-playbox-external-gateway.playbox-service.svc.cluster.local:80"
    
    - service: "http_status:404"