apiVersion: v1
kind: Namespace
metadata:
  name: scalex-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scalex-dash
  namespace: scalex-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scalex-dash-node-reader
  labels:
    app: scalex-dash
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scalex-dash-node-reader
  labels:
    app: scalex-dash
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scalex-dash-node-reader
subjects:
  - kind: ServiceAccount
    name: scalex-dash
    namespace: scalex-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scalex-dash-view
  labels:
    app: scalex-dash
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: scalex-dash
    namespace: scalex-system
---
apiVersion: v1
kind: Secret
metadata:
  name: scalex-dash-token
  namespace: scalex-system
  annotations:
    kubernetes.io/service-account.name: scalex-dash
type: kubernetes.io/service-account-token
