/// Pure functions for Kubernetes node kernel parameter tuning.
/// Generates sysctl configurations based on node role and hardware facts.
use std::collections::BTreeMap;

/// Recommended sysctl settings for Kubernetes nodes.
/// Returns ordered map for deterministic output.
pub fn generate_k8s_sysctl_params(role: &str) -> BTreeMap<String, String> {
    let mut params = BTreeMap::new();

    // Network performance (all nodes)
    params.insert("net.core.somaxconn".to_string(), "32768".to_string());
    params.insert(
        "net.core.netdev_max_backlog".to_string(),
        "5000".to_string(),
    );
    params.insert(
        "net.ipv4.tcp_max_syn_backlog".to_string(),
        "8096".to_string(),
    );
    params.insert("net.ipv4.ip_forward".to_string(), "1".to_string());
    params.insert(
        "net.bridge.bridge-nf-call-iptables".to_string(),
        "1".to_string(),
    );
    params.insert(
        "net.bridge.bridge-nf-call-ip6tables".to_string(),
        "1".to_string(),
    );

    // Memory management (all nodes)
    params.insert("vm.max_map_count".to_string(), "262144".to_string());
    params.insert("vm.swappiness".to_string(), "0".to_string());
    params.insert("vm.overcommit_memory".to_string(), "1".to_string());

    // File descriptors (all nodes)
    params.insert("fs.file-max".to_string(), "2097152".to_string());
    params.insert(
        "fs.inotify.max_user_watches".to_string(),
        "524288".to_string(),
    );
    params.insert(
        "fs.inotify.max_user_instances".to_string(),
        "8192".to_string(),
    );

    // Worker-specific: higher connection tracking for workloads
    if role == "worker" || role == "workload" {
        params.insert(
            "net.netfilter.nf_conntrack_max".to_string(),
            "1048576".to_string(),
        );
        params.insert("net.ipv4.tcp_tw_reuse".to_string(), "1".to_string());
    }

    // Control-plane specific: higher ARP cache for large clusters
    if role == "control-plane" || role == "management" {
        params.insert(
            "net.ipv4.neigh.default.gc_thresh3".to_string(),
            "8192".to_string(),
        );
    }

    params
}

/// Format sysctl params as sysctl.conf content.
pub fn format_sysctl_conf(params: &BTreeMap<String, String>) -> String {
    let mut lines = Vec::new();
    lines.push("# Kubernetes node kernel tuning".to_string());
    lines.push("# Generated by scalex kernel-tune".to_string());
    for (key, value) in params {
        lines.push(format!("{} = {}", key, value));
    }
    lines.push(String::new()); // trailing newline
    lines.join("\n")
}

/// Generate an Ansible task YAML snippet for applying sysctl params.
pub fn format_ansible_sysctl_tasks(params: &BTreeMap<String, String>) -> String {
    let mut lines = vec![
        "# Ansible tasks for kernel tuning (generated by scalex kernel-tune)".to_string(),
        "- name: Apply Kubernetes kernel tuning".to_string(),
        "  ansible.posix.sysctl:".to_string(),
        "    name: \"{{ item.key }}\"".to_string(),
        "    value: \"{{ item.value }}\"".to_string(),
        "    state: present".to_string(),
        "    sysctl_set: true".to_string(),
        "    reload: true".to_string(),
        "  loop:".to_string(),
    ];
    for (key, value) in params {
        lines.push(format!(
            "    - {{ key: \"{}\", value: \"{}\" }}",
            key, value
        ));
    }
    lines.push(String::new());
    lines.join("\n")
}

/// Diff current kernel params against recommended, return missing/different ones.
pub fn diff_kernel_params(
    current: &std::collections::HashMap<String, String>,
    recommended: &BTreeMap<String, String>,
) -> Vec<(String, Option<String>, String)> {
    // Returns: Vec<(param_name, current_value_or_none, recommended_value)>
    let mut diffs = Vec::new();
    for (key, rec_value) in recommended {
        match current.get(key) {
            Some(cur_value) if cur_value == rec_value => {} // OK
            Some(cur_value) => {
                diffs.push((key.clone(), Some(cur_value.clone()), rec_value.clone()));
            }
            None => {
                diffs.push((key.clone(), None, rec_value.clone()));
            }
        }
    }
    diffs
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    // ── generate_k8s_sysctl_params ──

    #[test]
    fn test_base_params_present_for_all_roles() {
        for role in &["control-plane", "worker", "management", "workload"] {
            let params = generate_k8s_sysctl_params(role);
            assert!(
                params.contains_key("net.ipv4.ip_forward"),
                "role {} missing ip_forward",
                role
            );
            assert!(
                params.contains_key("vm.swappiness"),
                "role {} missing swappiness",
                role
            );
            assert_eq!(
                params.get("vm.swappiness").unwrap(),
                "0",
                "swappiness must be 0 for K8s"
            );
            assert!(
                params.contains_key("fs.file-max"),
                "role {} missing file-max",
                role
            );
        }
    }

    #[test]
    fn test_worker_has_conntrack_max() {
        let params = generate_k8s_sysctl_params("worker");
        assert!(params.contains_key("net.netfilter.nf_conntrack_max"));
        assert_eq!(
            params.get("net.netfilter.nf_conntrack_max").unwrap(),
            "1048576"
        );
    }

    #[test]
    fn test_workload_has_conntrack_max() {
        let params = generate_k8s_sysctl_params("workload");
        assert!(params.contains_key("net.netfilter.nf_conntrack_max"));
    }

    #[test]
    fn test_control_plane_has_arp_cache() {
        let params = generate_k8s_sysctl_params("control-plane");
        assert!(params.contains_key("net.ipv4.neigh.default.gc_thresh3"));
        assert!(!params.contains_key("net.netfilter.nf_conntrack_max"));
    }

    #[test]
    fn test_management_has_arp_cache() {
        let params = generate_k8s_sysctl_params("management");
        assert!(params.contains_key("net.ipv4.neigh.default.gc_thresh3"));
    }

    #[test]
    fn test_unknown_role_gets_base_only() {
        let params = generate_k8s_sysctl_params("unknown");
        assert!(!params.contains_key("net.netfilter.nf_conntrack_max"));
        assert!(!params.contains_key("net.ipv4.neigh.default.gc_thresh3"));
        assert!(params.contains_key("net.ipv4.ip_forward"));
    }

    // ── format_sysctl_conf ──

    #[test]
    fn test_format_sysctl_conf_header() {
        let params = generate_k8s_sysctl_params("worker");
        let conf = format_sysctl_conf(&params);
        assert!(conf.starts_with("# Kubernetes node kernel tuning"));
        assert!(conf.contains("Generated by scalex kernel-tune"));
    }

    #[test]
    fn test_format_sysctl_conf_contains_params() {
        let params = generate_k8s_sysctl_params("worker");
        let conf = format_sysctl_conf(&params);
        assert!(conf.contains("vm.swappiness = 0"));
        assert!(conf.contains("net.ipv4.ip_forward = 1"));
    }

    #[test]
    fn test_format_sysctl_conf_sorted() {
        let params = generate_k8s_sysctl_params("worker");
        let conf = format_sysctl_conf(&params);
        let lines: Vec<&str> = conf
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .collect();
        let sorted = {
            let mut s = lines.clone();
            s.sort();
            s
        };
        assert_eq!(lines, sorted, "sysctl.conf must be sorted by key");
    }

    // ── format_ansible_sysctl_tasks ──

    #[test]
    fn test_format_ansible_tasks_structure() {
        let params = generate_k8s_sysctl_params("control-plane");
        let tasks = format_ansible_sysctl_tasks(&params);
        assert!(tasks.contains("ansible.posix.sysctl:"));
        assert!(tasks.contains("sysctl_set: true"));
        assert!(tasks.contains("reload: true"));
    }

    #[test]
    fn test_format_ansible_tasks_contains_params() {
        let params = generate_k8s_sysctl_params("worker");
        let tasks = format_ansible_sysctl_tasks(&params);
        assert!(tasks.contains("vm.swappiness"));
        assert!(tasks.contains("net.netfilter.nf_conntrack_max"));
    }

    // ── diff_kernel_params ──

    #[test]
    fn test_diff_all_matching() {
        let recommended = generate_k8s_sysctl_params("worker");
        let current: HashMap<String, String> = recommended
            .iter()
            .map(|(k, v)| (k.clone(), v.clone()))
            .collect();
        let diffs = diff_kernel_params(&current, &recommended);
        assert!(diffs.is_empty(), "all matching should produce no diffs");
    }

    #[test]
    fn test_diff_missing_param() {
        let recommended = generate_k8s_sysctl_params("worker");
        let current: HashMap<String, String> = HashMap::new();
        let diffs = diff_kernel_params(&current, &recommended);
        assert_eq!(
            diffs.len(),
            recommended.len(),
            "empty current should diff all params"
        );
        for (_, cur_val, _) in &diffs {
            assert!(cur_val.is_none());
        }
    }

    #[test]
    fn test_diff_wrong_value() {
        let recommended = generate_k8s_sysctl_params("worker");
        let mut current: HashMap<String, String> = recommended
            .iter()
            .map(|(k, v)| (k.clone(), v.clone()))
            .collect();
        current.insert("vm.swappiness".to_string(), "60".to_string());
        let diffs = diff_kernel_params(&current, &recommended);
        assert_eq!(diffs.len(), 1);
        assert_eq!(diffs[0].0, "vm.swappiness");
        assert_eq!(diffs[0].1, Some("60".to_string()));
        assert_eq!(diffs[0].2, "0");
    }
}
