use crate::models::cluster::{ClusterDef, CommonConfig};
use crate::models::sdi::{SdiPool, SdiSpec};

/// Generate kubespray inventory.ini content for a single cluster.
/// Pure function.
pub fn generate_inventory(cluster: &ClusterDef, sdi_spec: &SdiSpec) -> Result<String, String> {
    let pool = find_pool(sdi_spec, &cluster.cluster_sdi_resource_pool)?;

    let mut ini = String::new();

    // [all] section
    ini.push_str("[all]\n");
    for node in &pool.node_specs {
        ini.push_str(&format!(
            "{name} ansible_host={ip} ip={ip} etcd_member_name={name}\n",
            name = node.node_name,
            ip = node.ip,
        ));
    }
    ini.push('\n');

    // [kube_control_plane]
    ini.push_str("[kube_control_plane]\n");
    for node in &pool.node_specs {
        if node.roles.iter().any(|r| r == "control-plane") {
            ini.push_str(&format!("{}\n", node.node_name));
        }
    }
    ini.push('\n');

    // [etcd]
    ini.push_str("[etcd]\n");
    for node in &pool.node_specs {
        if node
            .roles
            .iter()
            .any(|r| r == "etcd" || r == "control-plane")
        {
            ini.push_str(&format!("{}\n", node.node_name));
        }
    }
    ini.push('\n');

    // [kube_node]
    ini.push_str("[kube_node]\n");
    for node in &pool.node_specs {
        if node.roles.iter().any(|r| r == "worker") {
            ini.push_str(&format!("{}\n", node.node_name));
        }
    }
    ini.push('\n');

    // [k8s_cluster:children]
    ini.push_str("[k8s_cluster:children]\nkube_control_plane\nkube_node\n");

    Ok(ini)
}

/// Generate kubespray cluster-vars (group_vars/all.yml) content.
/// Pure function: merges common config with cluster-specific overrides.
pub fn generate_cluster_vars(cluster: &ClusterDef, common: &CommonConfig) -> String {
    let mut vars = String::new();

    vars.push_str("# Auto-generated by scalex — do not edit manually\n");
    vars.push_str("---\n");

    // Kubernetes version
    vars.push_str(&format!(
        "kube_version: \"{}\"\n",
        common.kubernetes_version
    ));

    // Container runtime
    vars.push_str(&format!(
        "container_manager: \"{}\"\n",
        common.container_runtime
    ));

    // CNI — set to 'cni' for Cilium (managed by GitOps)
    if common.cni == "cilium" {
        vars.push_str("kube_network_plugin: cni\n");
        vars.push_str("kube_network_plugin_multus: false\n");
    } else {
        vars.push_str(&format!("kube_network_plugin: \"{}\"\n", common.cni));
    }

    // Kube-proxy removal (required for Cilium strict mode)
    if common.kube_proxy_remove {
        vars.push_str("kube_proxy_remove: true\n");
    }

    // CGroup driver
    vars.push_str(&format!(
        "kubelet_cgroup_driver: \"{}\"\n",
        common.cgroup_driver
    ));

    // Helm
    if common.helm_enabled {
        vars.push_str("helm_enabled: true\n");
    }

    // API server admission plugins
    if !common.kube_apiserver_admission_plugins.is_empty() {
        vars.push_str("kube_apiserver_enable_admission_plugins:\n");
        for plugin in &common.kube_apiserver_admission_plugins {
            vars.push_str(&format!("  - {plugin}\n"));
        }
    }

    // Cluster network
    vars.push_str(&format!(
        "kube_pods_subnet: \"{}\"\n",
        cluster.network.pod_cidr
    ));
    vars.push_str(&format!(
        "kube_service_addresses: \"{}\"\n",
        cluster.network.service_cidr
    ));
    vars.push_str(&format!("cluster_name: \"{}\"\n", cluster.cluster_name));
    vars.push_str(&format!("dns_domain: \"{}\"\n", cluster.network.dns_domain));

    // Cilium-specific
    if let Some(ref cilium) = cluster.cilium {
        vars.push_str("# Cilium ClusterMesh preparation\n");
        vars.push_str(&format!("cilium_cluster_id: {}\n", cilium.cluster_id));
        vars.push_str(&format!(
            "cilium_cluster_name: \"{}\"\n",
            cilium.cluster_name
        ));
    }

    // Native routing CIDR
    if let Some(ref cidr) = cluster.network.native_routing_cidr {
        vars.push_str(&format!("cilium_native_routing_cidr: \"{cidr}\"\n"));
    }

    // Extra vars from kubespray_extra_vars (as YAML)
    if let Some(ref extra) = cluster.kubespray_extra_vars {
        vars.push_str("\n# Cluster-specific extra vars\n");
        if let Ok(extra_str) = serde_yaml::to_string(extra) {
            // Remove the leading "---\n" that serde_yaml adds
            let trimmed = extra_str.strip_prefix("---\n").unwrap_or(&extra_str);
            vars.push_str(trimmed);
        }
    }

    vars
}

/// Generate kubespray inventory.ini for a baremetal cluster (no SDI layer).
/// Pure function.
pub fn generate_inventory_baremetal(cluster: &ClusterDef) -> Result<String, String> {
    if cluster.baremetal_nodes.is_empty() {
        return Err(format!(
            "Cluster '{}' has mode=baremetal but no baremetal_nodes defined",
            cluster.cluster_name
        ));
    }

    let mut ini = String::new();

    // [all] section
    ini.push_str("[all]\n");
    for node in &cluster.baremetal_nodes {
        ini.push_str(&format!(
            "{name} ansible_host={ip} ip={ip} etcd_member_name={name}\n",
            name = node.node_name,
            ip = node.ip,
        ));
    }
    ini.push('\n');

    // [kube_control_plane]
    ini.push_str("[kube_control_plane]\n");
    for node in &cluster.baremetal_nodes {
        if node.roles.iter().any(|r| r == "control-plane") {
            ini.push_str(&format!("{}\n", node.node_name));
        }
    }
    ini.push('\n');

    // [etcd]
    ini.push_str("[etcd]\n");
    for node in &cluster.baremetal_nodes {
        if node
            .roles
            .iter()
            .any(|r| r == "etcd" || r == "control-plane")
        {
            ini.push_str(&format!("{}\n", node.node_name));
        }
    }
    ini.push('\n');

    // [kube_node]
    ini.push_str("[kube_node]\n");
    for node in &cluster.baremetal_nodes {
        if node.roles.iter().any(|r| r == "worker") {
            ini.push_str(&format!("{}\n", node.node_name));
        }
    }
    ini.push('\n');

    // [k8s_cluster:children]
    ini.push_str("[k8s_cluster:children]\nkube_control_plane\nkube_node\n");

    Ok(ini)
}

/// Find the SDI pool matching a cluster's resource pool name.
fn find_pool<'a>(sdi_spec: &'a SdiSpec, pool_name: &str) -> Result<&'a SdiPool, String> {
    sdi_spec
        .spec
        .sdi_pools
        .iter()
        .find(|p| p.pool_name == pool_name)
        .ok_or_else(|| {
            format!(
                "SDI pool '{}' not found in spec. Available: {:?}",
                pool_name,
                sdi_spec
                    .spec
                    .sdi_pools
                    .iter()
                    .map(|p| &p.pool_name)
                    .collect::<Vec<_>>()
            )
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::cluster::*;
    use crate::models::sdi::*;

    fn make_sdi_spec() -> SdiSpec {
        SdiSpec {
            resource_pool: ResourcePoolConfig {
                name: "test".to_string(),
                network: NetworkConfig {
                    management_bridge: "br0".to_string(),
                    management_cidr: "192.168.88.0/24".to_string(),
                    gateway: "192.168.88.1".to_string(),
                    nameservers: vec!["8.8.8.8".to_string()],
                },
            },
            os_image: OsImageConfig {
                source: "https://example.com/img".to_string(),
                format: "qcow2".to_string(),
            },
            cloud_init: CloudInitConfig {
                ssh_authorized_keys_file: "~/.ssh/id.pub".to_string(),
                packages: vec![],
            },
            spec: SdiPoolsSpec {
                sdi_pools: vec![
                    SdiPool {
                        pool_name: "tower".to_string(),
                        purpose: "management".to_string(),
                        placement: PlacementConfig {
                            hosts: vec!["playbox-0".to_string()],
                            spread: false,
                        },
                        node_specs: vec![NodeSpec {
                            node_name: "tower-cp-0".to_string(),
                            ip: "192.168.88.100".to_string(),
                            cpu: 2,
                            mem_gb: 3,
                            disk_gb: 30,
                            host: None,
                            roles: vec!["control-plane".to_string(), "worker".to_string()],
                            devices: None,
                        }],
                    },
                    SdiPool {
                        pool_name: "sandbox".to_string(),
                        purpose: "workload".to_string(),
                        placement: PlacementConfig {
                            hosts: vec![],
                            spread: true,
                        },
                        node_specs: vec![
                            NodeSpec {
                                node_name: "sandbox-cp-0".to_string(),
                                ip: "192.168.88.110".to_string(),
                                cpu: 4,
                                mem_gb: 8,
                                disk_gb: 60,
                                host: Some("playbox-0".to_string()),
                                roles: vec!["control-plane".to_string(), "etcd".to_string()],
                                devices: None,
                            },
                            NodeSpec {
                                node_name: "sandbox-w-0".to_string(),
                                ip: "192.168.88.120".to_string(),
                                cpu: 8,
                                mem_gb: 16,
                                disk_gb: 100,
                                host: Some("playbox-1".to_string()),
                                roles: vec!["worker".to_string()],
                                devices: None,
                            },
                        ],
                    },
                ],
            },
        }
    }

    fn make_common() -> CommonConfig {
        CommonConfig {
            kubernetes_version: "1.33.1".to_string(),
            kubespray_version: "v2.30.0".to_string(),
            container_runtime: "containerd".to_string(),
            cni: "cilium".to_string(),
            cilium_version: "1.17.5".to_string(),
            kube_proxy_remove: true,
            cgroup_driver: "systemd".to_string(),
            helm_enabled: true,
            kube_apiserver_admission_plugins: vec!["NodeRestriction".to_string()],
        }
    }

    fn make_cluster_def(name: &str, pool: &str) -> ClusterDef {
        ClusterDef {
            cluster_name: name.to_string(),
            cluster_mode: crate::models::cluster::ClusterMode::Sdi,
            cluster_sdi_resource_pool: pool.to_string(),
            baremetal_nodes: vec![],
            cluster_role: "management".to_string(),
            network: ClusterNetwork {
                pod_cidr: "10.244.0.0/20".to_string(),
                service_cidr: "10.96.0.0/20".to_string(),
                dns_domain: "tower.local".to_string(),
                native_routing_cidr: None,
            },
            cilium: Some(CiliumConfig {
                cluster_id: 1,
                cluster_name: "tower".to_string(),
            }),
            kubespray_extra_vars: None,
        }
    }

    #[test]
    fn test_generate_inventory_tower() {
        let sdi = make_sdi_spec();
        let cluster = make_cluster_def("tower", "tower");
        let ini = generate_inventory(&cluster, &sdi).unwrap();

        assert!(ini.contains("[all]"));
        assert!(ini.contains("tower-cp-0 ansible_host=192.168.88.100"));
        assert!(ini.contains("[kube_control_plane]\ntower-cp-0"));
        assert!(ini.contains("[kube_node]\ntower-cp-0")); // tower-cp-0 has both roles
    }

    #[test]
    fn test_generate_inventory_sandbox() {
        let sdi = make_sdi_spec();
        let cluster = make_cluster_def("sandbox", "sandbox");
        let ini = generate_inventory(&cluster, &sdi).unwrap();

        assert!(ini.contains("sandbox-cp-0 ansible_host=192.168.88.110"));
        assert!(ini.contains("sandbox-w-0 ansible_host=192.168.88.120"));
        assert!(ini.contains("[kube_control_plane]\nsandbox-cp-0"));
        assert!(ini.contains("[kube_node]\nsandbox-w-0"));
    }

    #[test]
    fn test_generate_inventory_missing_pool() {
        let sdi = make_sdi_spec();
        let cluster = make_cluster_def("nonexistent", "does-not-exist");
        let result = generate_inventory(&cluster, &sdi);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("does-not-exist"));
    }

    #[test]
    fn test_generate_inventory_baremetal() {
        let cluster = ClusterDef {
            cluster_name: "prod".to_string(),
            cluster_mode: crate::models::cluster::ClusterMode::Baremetal,
            cluster_sdi_resource_pool: String::new(),
            baremetal_nodes: vec![
                crate::models::cluster::BaremetalNode {
                    node_name: "bm-cp-0".to_string(),
                    ip: "10.0.0.1".to_string(),
                    roles: vec!["control-plane".to_string(), "etcd".to_string()],
                },
                crate::models::cluster::BaremetalNode {
                    node_name: "bm-w-0".to_string(),
                    ip: "10.0.0.2".to_string(),
                    roles: vec!["worker".to_string()],
                },
            ],
            cluster_role: "workload".to_string(),
            network: ClusterNetwork {
                pod_cidr: "10.233.0.0/17".to_string(),
                service_cidr: "10.233.128.0/18".to_string(),
                dns_domain: "prod.local".to_string(),
                native_routing_cidr: None,
            },
            cilium: None,
            kubespray_extra_vars: None,
        };
        let ini = generate_inventory_baremetal(&cluster).unwrap();
        assert!(ini.contains("bm-cp-0 ansible_host=10.0.0.1"));
        assert!(ini.contains("bm-w-0 ansible_host=10.0.0.2"));
        assert!(ini.contains("[kube_control_plane]\nbm-cp-0"));
        assert!(ini.contains("[kube_node]\nbm-w-0"));
    }

    #[test]
    fn test_generate_inventory_baremetal_empty() {
        let cluster = ClusterDef {
            cluster_name: "empty".to_string(),
            cluster_mode: crate::models::cluster::ClusterMode::Baremetal,
            cluster_sdi_resource_pool: String::new(),
            baremetal_nodes: vec![],
            cluster_role: "workload".to_string(),
            network: ClusterNetwork {
                pod_cidr: "10.233.0.0/17".to_string(),
                service_cidr: "10.233.128.0/18".to_string(),
                dns_domain: "empty.local".to_string(),
                native_routing_cidr: None,
            },
            cilium: None,
            kubespray_extra_vars: None,
        };
        let result = generate_inventory_baremetal(&cluster);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("no baremetal_nodes"));
    }

    #[test]
    fn test_generate_cluster_vars() {
        let common = make_common();
        let cluster = make_cluster_def("tower", "tower");
        let vars = generate_cluster_vars(&cluster, &common);

        assert!(vars.contains("kube_version: \"1.33.1\""));
        assert!(vars.contains("kube_network_plugin: cni"));
        assert!(vars.contains("kube_proxy_remove: true"));
        assert!(vars.contains("kube_pods_subnet: \"10.244.0.0/20\""));
        assert!(vars.contains("dns_domain: \"tower.local\""));
        assert!(vars.contains("cilium_cluster_id: 1"));
        assert!(vars.contains("helm_enabled: true"));
        assert!(vars.contains("NodeRestriction"));
    }
}
