use crate::models::cluster::{ClusterDef, CommonConfig};
use crate::models::sdi::{SdiPool, SdiSpec};

/// Generate kubespray inventory.ini content for a single cluster.
/// Pure function.
pub fn generate_inventory(cluster: &ClusterDef, sdi_spec: &SdiSpec) -> Result<String, String> {
    let pool = find_pool(sdi_spec, &cluster.cluster_sdi_resource_pool)?;

    let mut ini = String::new();

    // [all] section
    ini.push_str("[all]\n");
    for node in &pool.node_specs {
        ini.push_str(&format!(
            "{name} ansible_host={ip} ip={ip} etcd_member_name={name}\n",
            name = node.node_name,
            ip = node.ip,
        ));
    }
    ini.push('\n');

    // [kube_control_plane]
    ini.push_str("[kube_control_plane]\n");
    for node in &pool.node_specs {
        if node.roles.iter().any(|r| r == "control-plane") {
            ini.push_str(&format!("{}\n", node.node_name));
        }
    }
    ini.push('\n');

    // [etcd]
    ini.push_str("[etcd]\n");
    for node in &pool.node_specs {
        if node
            .roles
            .iter()
            .any(|r| r == "etcd" || r == "control-plane")
        {
            ini.push_str(&format!("{}\n", node.node_name));
        }
    }
    ini.push('\n');

    // [kube_node]
    ini.push_str("[kube_node]\n");
    for node in &pool.node_specs {
        if node.roles.iter().any(|r| r == "worker") {
            ini.push_str(&format!("{}\n", node.node_name));
        }
    }
    ini.push('\n');

    // [k8s_cluster:children]
    ini.push_str("[k8s_cluster:children]\nkube_control_plane\nkube_node\n");

    Ok(ini)
}

/// Generate kubespray cluster-vars (group_vars/all.yml) content.
/// Pure function: merges common config with cluster-specific overrides.
pub fn generate_cluster_vars(cluster: &ClusterDef, common: &CommonConfig) -> String {
    let mut vars = String::new();

    vars.push_str("# Auto-generated by scalex — do not edit manually\n");
    vars.push_str("---\n");

    // Kubernetes version
    vars.push_str(&format!(
        "kube_version: \"{}\"\n",
        common.kubernetes_version
    ));

    // Container runtime
    vars.push_str(&format!(
        "container_manager: \"{}\"\n",
        common.container_runtime
    ));

    // CNI — set to 'cni' for Cilium (managed by GitOps)
    if common.cni == "cilium" {
        vars.push_str("kube_network_plugin: cni\n");
        vars.push_str("kube_network_plugin_multus: false\n");
    } else {
        vars.push_str(&format!("kube_network_plugin: \"{}\"\n", common.cni));
    }

    // Kube-proxy removal (required for Cilium strict mode)
    if common.kube_proxy_remove {
        vars.push_str("kube_proxy_remove: true\n");
    }

    // CGroup driver
    vars.push_str(&format!(
        "kubelet_cgroup_driver: \"{}\"\n",
        common.cgroup_driver
    ));

    // Helm
    if common.helm_enabled {
        vars.push_str("helm_enabled: true\n");
    }

    // Firewall / kube-vip
    vars.push_str(&format!(
        "firewalld_enabled: {}\n",
        common.firewalld_enabled
    ));
    vars.push_str(&format!("kube_vip_enabled: {}\n", common.kube_vip_enabled));

    // Gateway API
    if common.gateway_api_enabled {
        vars.push_str("gateway_api_enabled: true\n");
        if !common.gateway_api_version.is_empty() {
            vars.push_str(&format!(
                "gateway_api_version: \"{}\"\n",
                common.gateway_api_version
            ));
        }
    }

    // Graceful node shutdown
    if common.graceful_node_shutdown {
        vars.push_str("graceful_node_shutdown: true\n");
        vars.push_str(&format!(
            "graceful_node_shutdown_sec: {}\n",
            common.graceful_node_shutdown_sec
        ));
    }

    // Custom kubelet flags
    if !common.kubelet_custom_flags.is_empty() {
        vars.push_str("kubelet_custom_flags:\n");
        for flag in &common.kubelet_custom_flags {
            vars.push_str(&format!("  - \"{flag}\"\n"));
        }
    }

    // API server admission plugins
    if !common.kube_apiserver_admission_plugins.is_empty() {
        vars.push_str("kube_apiserver_enable_admission_plugins:\n");
        for plugin in &common.kube_apiserver_admission_plugins {
            vars.push_str(&format!("  - {plugin}\n"));
        }
    }

    // Addon disablement — prevent Kubespray/ArgoCD conflicts (DataX pattern).
    // These are managed by ArgoCD GitOps; Kubespray must not deploy them.
    vars.push_str("\n# Addon disablement (managed by ArgoCD)\n");
    vars.push_str("cert_manager_enabled: false\n");
    vars.push_str("argocd_enabled: false\n");
    vars.push_str("metallb_enabled: false\n");
    vars.push_str("ingress_nginx_enabled: false\n");
    vars.push_str("local_path_provisioner_enabled: false\n");
    vars.push_str("node_feature_discovery_enabled: false\n");
    vars.push_str("metrics_server_enabled: false\n");
    vars.push_str("registry_enabled: false\n");

    // Cluster network
    vars.push_str(&format!(
        "kube_pods_subnet: \"{}\"\n",
        cluster.network.pod_cidr
    ));
    vars.push_str(&format!(
        "kube_service_addresses: \"{}\"\n",
        cluster.network.service_cidr
    ));
    vars.push_str(&format!("cluster_name: \"{}\"\n", cluster.cluster_name));
    vars.push_str(&format!("dns_domain: \"{}\"\n", cluster.network.dns_domain));

    // Cilium-specific
    if let Some(ref cilium) = cluster.cilium {
        vars.push_str("# Cilium ClusterMesh preparation\n");
        vars.push_str(&format!("cilium_cluster_id: {}\n", cilium.cluster_id));
        vars.push_str(&format!(
            "cilium_cluster_name: \"{}\"\n",
            cilium.cluster_name
        ));
    }

    // Kubeconfig and kubectl on Ansible host
    if common.kubeconfig_localhost {
        vars.push_str("kubeconfig_localhost: true\n");
        vars.push_str("kubeconfig_localhost_ansible_host: true\n");
    }
    if common.kubectl_localhost {
        vars.push_str("kubectl_localhost: true\n");
    }

    // Node-local DNS cache
    if common.enable_nodelocaldns {
        vars.push_str("enable_nodelocaldns: true\n");
    }

    // Network node prefix
    vars.push_str(&format!(
        "kube_network_node_prefix: {}\n",
        common.kube_network_node_prefix
    ));

    // NTP
    if common.ntp_enabled {
        vars.push_str("ntp_enabled: true\n");
    }

    // Etcd deployment type (DataX production pattern: host)
    vars.push_str(&format!(
        "etcd_deployment_type: {}\n",
        common.etcd_deployment_type
    ));

    // DNS mode (DataX production pattern: coredns)
    vars.push_str(&format!("dns_mode: {}\n", common.dns_mode));

    // OIDC authentication (Keycloak integration)
    if let Some(ref oidc) = cluster.oidc {
        if oidc.enabled {
            vars.push_str("\n# OIDC authentication (Keycloak)\n");
            vars.push_str("kube_oidc_auth: true\n");
            vars.push_str(&format!("kube_oidc_client_id: \"{}\"\n", oidc.client_id));
            vars.push_str(&format!("kube_oidc_url: \"{}\"\n", oidc.issuer_url));
            vars.push_str(&format!(
                "kube_oidc_username_claim: \"{}\"\n",
                oidc.username_claim
            ));
            vars.push_str(&format!(
                "kube_oidc_username_prefix: \"{}\"\n",
                oidc.username_prefix
            ));
            vars.push_str(&format!(
                "kube_oidc_groups_claim: \"{}\"\n",
                oidc.groups_claim
            ));
            vars.push_str(&format!(
                "kube_oidc_groups_prefix: \"{}\"\n",
                oidc.groups_prefix
            ));
        }
    }

    // Native routing CIDR
    if let Some(ref cidr) = cluster.network.native_routing_cidr {
        vars.push_str(&format!("cilium_native_routing_cidr: \"{cidr}\"\n"));
    }

    // Extra vars from kubespray_extra_vars (as YAML)
    if let Some(ref extra) = cluster.kubespray_extra_vars {
        vars.push_str("\n# Cluster-specific extra vars\n");
        if let Ok(extra_str) = serde_yaml::to_string(extra) {
            // Remove the leading "---\n" that serde_yaml adds
            let trimmed = extra_str.strip_prefix("---\n").unwrap_or(&extra_str);
            vars.push_str(trimmed);
        }
    }

    vars
}

/// Generate kubespray inventory.ini for a baremetal cluster (no SDI layer).
/// Pure function.
pub fn generate_inventory_baremetal(cluster: &ClusterDef) -> Result<String, String> {
    if cluster.baremetal_nodes.is_empty() {
        return Err(format!(
            "Cluster '{}' has mode=baremetal but no baremetal_nodes defined",
            cluster.cluster_name
        ));
    }

    let has_control_plane = cluster
        .baremetal_nodes
        .iter()
        .any(|n| n.roles.iter().any(|r| r == "control-plane"));
    if !has_control_plane {
        return Err(format!(
            "Cluster '{}' has no node with control-plane role (Kubespray requires at least one)",
            cluster.cluster_name
        ));
    }

    let mut ini = String::new();

    // [all] section
    ini.push_str("[all]\n");
    for node in &cluster.baremetal_nodes {
        ini.push_str(&format!(
            "{name} ansible_host={ip} ip={ip} etcd_member_name={name}\n",
            name = node.node_name,
            ip = node.ip,
        ));
    }
    ini.push('\n');

    // [kube_control_plane]
    ini.push_str("[kube_control_plane]\n");
    for node in &cluster.baremetal_nodes {
        if node.roles.iter().any(|r| r == "control-plane") {
            ini.push_str(&format!("{}\n", node.node_name));
        }
    }
    ini.push('\n');

    // [etcd]
    ini.push_str("[etcd]\n");
    for node in &cluster.baremetal_nodes {
        if node
            .roles
            .iter()
            .any(|r| r == "etcd" || r == "control-plane")
        {
            ini.push_str(&format!("{}\n", node.node_name));
        }
    }
    ini.push('\n');

    // [kube_node]
    ini.push_str("[kube_node]\n");
    for node in &cluster.baremetal_nodes {
        if node.roles.iter().any(|r| r == "worker") {
            ini.push_str(&format!("{}\n", node.node_name));
        }
    }
    ini.push('\n');

    // [k8s_cluster:children]
    ini.push_str("[k8s_cluster:children]\nkube_control_plane\nkube_node\n");

    Ok(ini)
}

/// Find the SDI pool matching a cluster's resource pool name.
fn find_pool<'a>(sdi_spec: &'a SdiSpec, pool_name: &str) -> Result<&'a SdiPool, String> {
    sdi_spec
        .spec
        .sdi_pools
        .iter()
        .find(|p| p.pool_name == pool_name)
        .ok_or_else(|| {
            format!(
                "SDI pool '{}' not found in spec. Available: {:?}",
                pool_name,
                sdi_spec
                    .spec
                    .sdi_pools
                    .iter()
                    .map(|p| &p.pool_name)
                    .collect::<Vec<_>>()
            )
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::cluster::*;
    use crate::models::sdi::*;

    fn make_sdi_spec() -> SdiSpec {
        SdiSpec {
            resource_pool: ResourcePoolConfig {
                name: "test".to_string(),
                network: NetworkConfig {
                    management_bridge: "br0".to_string(),
                    management_cidr: "192.168.88.0/24".to_string(),
                    gateway: "192.168.88.1".to_string(),
                    nameservers: vec!["8.8.8.8".to_string()],
                },
            },
            os_image: OsImageConfig {
                source: "https://example.com/img".to_string(),
                format: "qcow2".to_string(),
            },
            cloud_init: CloudInitConfig {
                ssh_authorized_keys_file: "~/.ssh/id.pub".to_string(),
                packages: vec![],
            },
            spec: SdiPoolsSpec {
                sdi_pools: vec![
                    SdiPool {
                        pool_name: "tower".to_string(),
                        purpose: "management".to_string(),
                        placement: PlacementConfig {
                            hosts: vec!["playbox-0".to_string()],
                            spread: false,
                        },
                        node_specs: vec![NodeSpec {
                            node_name: "tower-cp-0".to_string(),
                            ip: "192.168.88.100".to_string(),
                            cpu: 2,
                            mem_gb: 3,
                            disk_gb: 30,
                            host: None,
                            roles: vec!["control-plane".to_string(), "worker".to_string()],
                            devices: None,
                        }],
                    },
                    SdiPool {
                        pool_name: "sandbox".to_string(),
                        purpose: "workload".to_string(),
                        placement: PlacementConfig {
                            hosts: vec![],
                            spread: true,
                        },
                        node_specs: vec![
                            NodeSpec {
                                node_name: "sandbox-cp-0".to_string(),
                                ip: "192.168.88.110".to_string(),
                                cpu: 4,
                                mem_gb: 8,
                                disk_gb: 60,
                                host: Some("playbox-0".to_string()),
                                roles: vec!["control-plane".to_string(), "etcd".to_string()],
                                devices: None,
                            },
                            NodeSpec {
                                node_name: "sandbox-w-0".to_string(),
                                ip: "192.168.88.120".to_string(),
                                cpu: 8,
                                mem_gb: 16,
                                disk_gb: 100,
                                host: Some("playbox-1".to_string()),
                                roles: vec!["worker".to_string()],
                                devices: None,
                            },
                        ],
                    },
                ],
            },
        }
    }

    fn make_common() -> CommonConfig {
        CommonConfig {
            kubernetes_version: "1.33.1".to_string(),
            kubespray_version: "v2.30.0".to_string(),
            container_runtime: "containerd".to_string(),
            cni: "cilium".to_string(),
            cilium_version: "1.17.5".to_string(),
            kube_proxy_remove: true,
            cgroup_driver: "systemd".to_string(),
            helm_enabled: true,
            kube_apiserver_admission_plugins: vec!["NodeRestriction".to_string()],
            firewalld_enabled: false,
            kube_vip_enabled: false,
            gateway_api_enabled: false,
            gateway_api_version: String::new(),
            graceful_node_shutdown: false,
            graceful_node_shutdown_sec: 120,
            kubelet_custom_flags: vec![],
            kubeconfig_localhost: true,
            kubectl_localhost: true,
            enable_nodelocaldns: true,
            kube_network_node_prefix: 24,
            ntp_enabled: true,
            etcd_deployment_type: "host".to_string(),
            dns_mode: "coredns".to_string(),
        }
    }

    fn make_cluster_def(name: &str, pool: &str) -> ClusterDef {
        ClusterDef {
            cluster_name: name.to_string(),
            cluster_mode: crate::models::cluster::ClusterMode::Sdi,
            cluster_sdi_resource_pool: pool.to_string(),
            baremetal_nodes: vec![],
            cluster_role: "management".to_string(),
            network: ClusterNetwork {
                pod_cidr: "10.244.0.0/20".to_string(),
                service_cidr: "10.96.0.0/20".to_string(),
                dns_domain: "tower.local".to_string(),
                native_routing_cidr: None,
            },
            cilium: Some(CiliumConfig {
                cluster_id: 1,
                cluster_name: "tower".to_string(),
            }),
            oidc: None,
            kubespray_extra_vars: None,
            ssh_user: None,
        }
    }

    #[test]
    fn test_generate_inventory_tower() {
        let sdi = make_sdi_spec();
        let cluster = make_cluster_def("tower", "tower");
        let ini = generate_inventory(&cluster, &sdi).unwrap();

        assert!(ini.contains("[all]"));
        assert!(ini.contains("tower-cp-0 ansible_host=192.168.88.100"));
        assert!(ini.contains("[kube_control_plane]\ntower-cp-0"));
        assert!(ini.contains("[kube_node]\ntower-cp-0")); // tower-cp-0 has both roles
    }

    #[test]
    fn test_generate_inventory_sandbox() {
        let sdi = make_sdi_spec();
        let cluster = make_cluster_def("sandbox", "sandbox");
        let ini = generate_inventory(&cluster, &sdi).unwrap();

        assert!(ini.contains("sandbox-cp-0 ansible_host=192.168.88.110"));
        assert!(ini.contains("sandbox-w-0 ansible_host=192.168.88.120"));
        assert!(ini.contains("[kube_control_plane]\nsandbox-cp-0"));
        assert!(ini.contains("[kube_node]\nsandbox-w-0"));
    }

    #[test]
    fn test_generate_inventory_missing_pool() {
        let sdi = make_sdi_spec();
        let cluster = make_cluster_def("nonexistent", "does-not-exist");
        let result = generate_inventory(&cluster, &sdi);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("does-not-exist"));
    }

    #[test]
    fn test_generate_inventory_baremetal() {
        let cluster = ClusterDef {
            cluster_name: "prod".to_string(),
            cluster_mode: crate::models::cluster::ClusterMode::Baremetal,
            cluster_sdi_resource_pool: String::new(),
            baremetal_nodes: vec![
                crate::models::cluster::BaremetalNode {
                    node_name: "bm-cp-0".to_string(),
                    ip: "10.0.0.1".to_string(),
                    roles: vec!["control-plane".to_string(), "etcd".to_string()],
                },
                crate::models::cluster::BaremetalNode {
                    node_name: "bm-w-0".to_string(),
                    ip: "10.0.0.2".to_string(),
                    roles: vec!["worker".to_string()],
                },
            ],
            cluster_role: "workload".to_string(),
            network: ClusterNetwork {
                pod_cidr: "10.233.0.0/17".to_string(),
                service_cidr: "10.233.128.0/18".to_string(),
                dns_domain: "prod.local".to_string(),
                native_routing_cidr: None,
            },
            cilium: None,
            oidc: None,
            kubespray_extra_vars: None,
            ssh_user: None,
        };
        let ini = generate_inventory_baremetal(&cluster).unwrap();
        assert!(ini.contains("bm-cp-0 ansible_host=10.0.0.1"));
        assert!(ini.contains("bm-w-0 ansible_host=10.0.0.2"));
        assert!(ini.contains("[kube_control_plane]\nbm-cp-0"));
        assert!(ini.contains("[kube_node]\nbm-w-0"));
    }

    #[test]
    fn test_generate_inventory_baremetal_empty() {
        let cluster = ClusterDef {
            cluster_name: "empty".to_string(),
            cluster_mode: crate::models::cluster::ClusterMode::Baremetal,
            cluster_sdi_resource_pool: String::new(),
            baremetal_nodes: vec![],
            cluster_role: "workload".to_string(),
            network: ClusterNetwork {
                pod_cidr: "10.233.0.0/17".to_string(),
                service_cidr: "10.233.128.0/18".to_string(),
                dns_domain: "empty.local".to_string(),
                native_routing_cidr: None,
            },
            cilium: None,
            oidc: None,
            kubespray_extra_vars: None,
            ssh_user: None,
        };
        let result = generate_inventory_baremetal(&cluster);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("no baremetal_nodes"));
    }

    #[test]
    fn test_generate_cluster_vars() {
        let common = make_common();
        let cluster = make_cluster_def("tower", "tower");
        let vars = generate_cluster_vars(&cluster, &common);

        assert!(vars.contains("kube_version: \"1.33.1\""));
        assert!(vars.contains("kube_network_plugin: cni"));
        assert!(vars.contains("kube_proxy_remove: true"));
        assert!(vars.contains("kube_pods_subnet: \"10.244.0.0/20\""));
        assert!(vars.contains("dns_domain: \"tower.local\""));
        assert!(vars.contains("cilium_cluster_id: 1"));
        assert!(vars.contains("helm_enabled: true"));
        assert!(vars.contains("NodeRestriction"));
    }

    #[test]
    fn test_generate_cluster_vars_datax_production_settings() {
        // DataX kubespray production settings that must be present
        let mut common = make_common();
        common.kubeconfig_localhost = true;
        common.kubectl_localhost = true;
        common.enable_nodelocaldns = true;
        common.kube_network_node_prefix = 24;
        common.ntp_enabled = true;

        let cluster = make_cluster_def("tower", "tower");
        let vars = generate_cluster_vars(&cluster, &common);

        // DataX production-required settings
        assert!(
            vars.contains("kubeconfig_localhost: true"),
            "missing kubeconfig_localhost"
        );
        assert!(
            vars.contains("kubectl_localhost: true"),
            "missing kubectl_localhost"
        );
        assert!(
            vars.contains("kubeconfig_localhost_ansible_host: true"),
            "missing kubeconfig_localhost_ansible_host"
        );
        assert!(
            vars.contains("enable_nodelocaldns: true"),
            "missing enable_nodelocaldns"
        );
        assert!(
            vars.contains("kube_network_node_prefix: 24"),
            "missing kube_network_node_prefix"
        );
        assert!(vars.contains("ntp_enabled: true"), "missing ntp_enabled");
    }

    #[test]
    fn test_generate_cluster_vars_datax_settings() {
        let mut common = make_common();
        common.firewalld_enabled = false;
        common.kube_vip_enabled = false;
        common.gateway_api_enabled = true;
        common.gateway_api_version = "1.3.0".to_string();
        common.graceful_node_shutdown = true;
        common.graceful_node_shutdown_sec = 120;
        common.kubelet_custom_flags = vec!["--node-ip={{ ip }}".to_string()];

        let cluster = make_cluster_def("tower", "tower");
        let vars = generate_cluster_vars(&cluster, &common);

        // DataX-required settings
        assert!(vars.contains("firewalld_enabled: false"));
        assert!(vars.contains("kube_vip_enabled: false"));
        assert!(vars.contains("gateway_api_enabled: true"));
        assert!(vars.contains("gateway_api_version: \"1.3.0\""));
        assert!(vars.contains("graceful_node_shutdown: true"));
        assert!(vars.contains("graceful_node_shutdown_sec: 120"));
        assert!(vars.contains("kubelet_custom_flags:"));
        assert!(vars.contains("--node-ip={{ ip }}"));
    }

    #[test]
    fn test_generate_cluster_vars_oidc_settings() {
        let common = make_common();
        let mut cluster = make_cluster_def("sandbox", "sandbox");
        cluster.oidc = Some(crate::models::cluster::OidcConfig {
            enabled: true,
            client_id: "kubernetes".to_string(),
            issuer_url: "https://auth.jinwang.dev/realms/kubernetes".to_string(),
            username_claim: "preferred_username".to_string(),
            username_prefix: "oidc:".to_string(),
            groups_claim: "groups".to_string(),
            groups_prefix: "oidc:".to_string(),
        });

        let vars = generate_cluster_vars(&cluster, &common);

        // Must contain all OIDC settings for kube-apiserver
        assert!(
            vars.contains("kube_oidc_auth: true"),
            "missing kube_oidc_auth"
        );
        assert!(
            vars.contains("kube_oidc_client_id: \"kubernetes\""),
            "missing kube_oidc_client_id"
        );
        assert!(
            vars.contains("kube_oidc_url: \"https://auth.jinwang.dev/realms/kubernetes\""),
            "missing kube_oidc_url"
        );
        assert!(
            vars.contains("kube_oidc_username_claim: \"preferred_username\""),
            "missing kube_oidc_username_claim"
        );
        assert!(
            vars.contains("kube_oidc_username_prefix: \"oidc:\""),
            "missing kube_oidc_username_prefix"
        );
        assert!(
            vars.contains("kube_oidc_groups_claim: \"groups\""),
            "missing kube_oidc_groups_claim"
        );
        assert!(
            vars.contains("kube_oidc_groups_prefix: \"oidc:\""),
            "missing kube_oidc_groups_prefix"
        );
    }

    #[test]
    fn test_generate_cluster_vars_no_oidc() {
        let common = make_common();
        let cluster = make_cluster_def("tower", "tower");
        // oidc is None by default
        let vars = generate_cluster_vars(&cluster, &common);

        // Must NOT contain OIDC settings when disabled
        assert!(
            !vars.contains("kube_oidc_auth"),
            "should not have kube_oidc_auth when oidc is None"
        );
    }

    #[test]
    fn test_cluster_vars_valid_yaml() {
        // Generated cluster-vars must be parseable as valid YAML
        let common = make_common();
        let cluster = make_cluster_def("tower", "tower");
        let vars = generate_cluster_vars(&cluster, &common);
        let parsed: serde_yaml::Value = serde_yaml::from_str(&vars)
            .unwrap_or_else(|e| panic!("cluster-vars is not valid YAML: {e}\n---\n{vars}"));
        assert!(parsed.is_mapping(), "parsed YAML must be a mapping");
    }

    #[test]
    fn test_cluster_vars_valid_yaml_full_config() {
        // Full production config (all features enabled) must also be valid YAML
        let mut common = make_common();
        common.gateway_api_enabled = true;
        common.gateway_api_version = "1.3.0".to_string();
        common.graceful_node_shutdown = true;
        common.graceful_node_shutdown_sec = 120;
        common.kubelet_custom_flags = vec!["--node-ip={{ ip }}".to_string()];

        let mut cluster = make_cluster_def("sandbox", "sandbox");
        cluster.network.native_routing_cidr = Some("10.233.0.0/16".to_string());
        cluster.oidc = Some(crate::models::cluster::OidcConfig {
            enabled: true,
            client_id: "kubernetes".to_string(),
            issuer_url: "https://auth.jinwang.dev/realms/kubernetes".to_string(),
            username_claim: "preferred_username".to_string(),
            username_prefix: "oidc:".to_string(),
            groups_claim: "groups".to_string(),
            groups_prefix: "oidc:".to_string(),
        });
        cluster.kubespray_extra_vars = Some(serde_yaml::from_str(
            "kube_api_anonymous_auth: true\nkubelet_config_extra_args:\n  systemReserved:\n    cpu: \"200m\"",
        ).unwrap());

        let vars = generate_cluster_vars(&cluster, &common);
        let parsed: serde_yaml::Value = serde_yaml::from_str(&vars)
            .unwrap_or_else(|e| panic!("full cluster-vars is not valid YAML: {e}\n---\n{vars}"));
        assert!(parsed.is_mapping());
    }

    #[test]
    fn test_cluster_vars_contains_all_required_keys() {
        // Kubespray requires these keys in group_vars/all.yml
        let common = make_common();
        let cluster = make_cluster_def("tower", "tower");
        let vars = generate_cluster_vars(&cluster, &common);
        let parsed: serde_yaml::Mapping = serde_yaml::from_str(&vars).unwrap();

        let required_keys = [
            "kube_version",
            "container_manager",
            "kube_network_plugin",
            "kubelet_cgroup_driver",
            "kube_pods_subnet",
            "kube_service_addresses",
            "cluster_name",
            "dns_domain",
            "firewalld_enabled",
            "kube_vip_enabled",
            "kube_network_node_prefix",
            // Addon disablement — prevent Kubespray/ArgoCD conflicts (DataX pattern)
            "cert_manager_enabled",
            "argocd_enabled",
            "metallb_enabled",
            "ingress_nginx_enabled",
            "local_path_provisioner_enabled",
            "node_feature_discovery_enabled",
            "metrics_server_enabled",
            "registry_enabled",
            // DataX production settings
            "etcd_deployment_type",
            "dns_mode",
        ];

        for key in &required_keys {
            assert!(
                parsed.contains_key(serde_yaml::Value::String(key.to_string())),
                "missing required kubespray key: {key}"
            );
        }
    }

    /// DataX pattern: Kubespray addons that are managed by ArgoCD must be explicitly disabled
    /// in cluster-vars to prevent Kubespray from deploying them (causing conflicts).
    #[test]
    fn test_cluster_vars_addon_disablement_prevents_argocd_conflicts() {
        let common = make_common();
        let cluster = make_cluster_def("tower", "tower");
        let vars = generate_cluster_vars(&cluster, &common);

        // These addons are deployed via ArgoCD GitOps — Kubespray must NOT deploy them
        let disabled_addons = [
            ("cert_manager_enabled", "false"),
            ("argocd_enabled", "false"),
            ("metallb_enabled", "false"),
            ("ingress_nginx_enabled", "false"),
            ("local_path_provisioner_enabled", "false"),
            ("node_feature_discovery_enabled", "false"),
            ("metrics_server_enabled", "false"),
            ("registry_enabled", "false"),
        ];

        for (key, expected) in &disabled_addons {
            assert!(
                vars.contains(&format!("{key}: {expected}")),
                "missing addon disablement: {key}: {expected}\n--- generated vars ---\n{vars}"
            );
        }
    }

    /// DataX legacy addons.yml disables metrics_server and registry — Kubespray must match.
    #[test]
    fn test_cluster_vars_datax_addon_disablement_metrics_and_registry() {
        let common = make_common();
        let cluster = make_cluster_def("tower", "tower");
        let vars = generate_cluster_vars(&cluster, &common);

        let datax_disabled = [
            ("metrics_server_enabled", "false"),
            ("registry_enabled", "false"),
        ];

        for (key, expected) in &datax_disabled {
            assert!(
                vars.contains(&format!("{key}: {expected}")),
                "missing DataX addon disablement: {key}: {expected}\n--- generated vars ---\n{vars}"
            );
        }
    }

    #[test]
    fn test_inventory_contains_all_required_sections() {
        let sdi = make_sdi_spec();
        let cluster = make_cluster_def("sandbox", "sandbox");
        let ini = generate_inventory(&cluster, &sdi).unwrap();

        let required_sections = [
            "[all]",
            "[kube_control_plane]",
            "[etcd]",
            "[kube_node]",
            "[k8s_cluster:children]",
        ];

        for section in &required_sections {
            assert!(
                ini.contains(section),
                "inventory missing required section: {section}"
            );
        }
    }

    #[test]
    fn test_inventory_baremetal_contains_all_required_sections() {
        let cluster = ClusterDef {
            cluster_name: "prod".to_string(),
            cluster_mode: crate::models::cluster::ClusterMode::Baremetal,
            cluster_sdi_resource_pool: String::new(),
            baremetal_nodes: vec![
                crate::models::cluster::BaremetalNode {
                    node_name: "bm-0".to_string(),
                    ip: "10.0.0.1".to_string(),
                    roles: vec!["control-plane".to_string(), "etcd".to_string()],
                },
                crate::models::cluster::BaremetalNode {
                    node_name: "bm-1".to_string(),
                    ip: "10.0.0.2".to_string(),
                    roles: vec!["worker".to_string()],
                },
            ],
            cluster_role: "workload".to_string(),
            network: ClusterNetwork {
                pod_cidr: "10.233.0.0/17".to_string(),
                service_cidr: "10.233.128.0/18".to_string(),
                dns_domain: "prod.local".to_string(),
                native_routing_cidr: None,
            },
            cilium: None,
            oidc: None,
            kubespray_extra_vars: None,
            ssh_user: None,
        };
        let ini = generate_inventory_baremetal(&cluster).unwrap();

        for section in &[
            "[all]",
            "[kube_control_plane]",
            "[etcd]",
            "[kube_node]",
            "[k8s_cluster:children]",
        ] {
            assert!(
                ini.contains(section),
                "baremetal inventory missing: {section}"
            );
        }
    }

    #[test]
    fn test_generate_cluster_vars_oidc_disabled() {
        let common = make_common();
        let mut cluster = make_cluster_def("sandbox", "sandbox");
        cluster.oidc = Some(crate::models::cluster::OidcConfig {
            enabled: false,
            client_id: "kubernetes".to_string(),
            issuer_url: "https://auth.example.com/realms/k8s".to_string(),
            ..Default::default()
        });

        let vars = generate_cluster_vars(&cluster, &common);

        // OIDC disabled explicitly — must not emit OIDC vars
        assert!(
            !vars.contains("kube_oidc_auth"),
            "should not have kube_oidc_auth when oidc.enabled is false"
        );
    }

    /// Full pipeline dry-run: parse example configs → generate inventory + cluster-vars for each cluster.
    /// Ensures the entire data flow works end-to-end without side effects.
    #[test]
    fn test_full_pipeline_dryrun() {
        // Parse the same YAML content as in config examples
        let k8s_yaml = r#"
config:
  common:
    kubernetes_version: "1.33.1"
    kubespray_version: "v2.30.0"
    container_runtime: "containerd"
    cni: "cilium"
    cilium_version: "1.17.5"
    kube_proxy_remove: true
    cgroup_driver: "systemd"
    helm_enabled: true
    kube_apiserver_admission_plugins:
      - NodeRestriction
      - PodTolerationRestriction
    firewalld_enabled: false
    kube_vip_enabled: false
    graceful_node_shutdown: true
    graceful_node_shutdown_sec: 120
    kubelet_custom_flags:
      - "--node-ip={{ ip }}"
    gateway_api_enabled: true
    gateway_api_version: "1.3.0"
    kubeconfig_localhost: true
    kubectl_localhost: true
    enable_nodelocaldns: true
    kube_network_node_prefix: 24
    ntp_enabled: true
  clusters:
    - cluster_name: "tower"
      cluster_sdi_resource_pool: "tower"
      cluster_role: "management"
      network:
        pod_cidr: "10.244.0.0/20"
        service_cidr: "10.96.0.0/20"
        dns_domain: "tower.local"
      cilium:
        cluster_id: 1
        cluster_name: "tower"
      kubespray_extra_vars:
        kube_api_anonymous_auth: true
    - cluster_name: "sandbox"
      cluster_sdi_resource_pool: "sandbox"
      cluster_role: "workload"
      network:
        pod_cidr: "10.233.0.0/17"
        service_cidr: "10.233.128.0/18"
        dns_domain: "sandbox.local"
        native_routing_cidr: "10.233.0.0/16"
      cilium:
        cluster_id: 2
        cluster_name: "sandbox"
      oidc:
        enabled: true
        client_id: "kubernetes"
        issuer_url: "https://auth.jinwang.dev/realms/kubernetes"
      kubespray_extra_vars:
        kube_api_anonymous_auth: true
  argocd:
    namespace: "argocd"
    repo_url: "https://github.com/JinwangMok/ScaleX-POD-mini.git"
    repo_branch: "main"
    tower_manages: ["sandbox"]
"#;

        let sdi_yaml = r#"
resource_pool:
  name: "playbox-pool"
  network:
    management_bridge: "br0"
    management_cidr: "192.168.88.0/24"
    gateway: "192.168.88.1"
    nameservers: ["8.8.8.8"]
os_image:
  source: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
  format: "qcow2"
cloud_init:
  ssh_authorized_keys_file: "~/.ssh/id_ed25519.pub"
  packages: [curl, nfs-common]
spec:
  sdi_pools:
    - pool_name: "tower"
      purpose: "management"
      placement:
        hosts: [playbox-0]
      node_specs:
        - node_name: "tower-cp-0"
          ip: "192.168.88.100"
          cpu: 2
          mem_gb: 3
          disk_gb: 30
          roles: [control-plane, worker]
    - pool_name: "sandbox"
      purpose: "workload"
      placement:
        spread: true
      node_specs:
        - node_name: "sandbox-cp-0"
          ip: "192.168.88.110"
          cpu: 4
          mem_gb: 8
          disk_gb: 60
          host: "playbox-0"
          roles: [control-plane, etcd]
        - node_name: "sandbox-w-0"
          ip: "192.168.88.120"
          cpu: 8
          mem_gb: 16
          disk_gb: 100
          host: "playbox-1"
          roles: [worker]
"#;

        // Step 1: Parse configs
        let k8s_config: crate::models::cluster::K8sClustersConfig =
            serde_yaml::from_str(k8s_yaml).expect("failed to parse k8s-clusters config");
        let sdi_spec: crate::models::sdi::SdiSpec =
            serde_yaml::from_str(sdi_yaml).expect("failed to parse sdi-specs config");

        // Step 2: Generate inventory + cluster-vars for each cluster
        for cluster in &k8s_config.config.clusters {
            // Inventory
            let inventory = generate_inventory(cluster, &sdi_spec)
                .unwrap_or_else(|e| panic!("inventory failed for {}: {e}", cluster.cluster_name));
            assert!(
                inventory.contains("[all]"),
                "{} inventory missing [all]",
                cluster.cluster_name
            );
            assert!(
                inventory.contains("[k8s_cluster:children]"),
                "{} inventory missing [k8s_cluster:children]",
                cluster.cluster_name
            );

            // Cluster vars — must be valid YAML
            let vars = generate_cluster_vars(cluster, &k8s_config.config.common);
            let parsed: serde_yaml::Value = serde_yaml::from_str(&vars).unwrap_or_else(|e| {
                panic!(
                    "{} cluster-vars invalid YAML: {e}\n---\n{vars}",
                    cluster.cluster_name
                )
            });
            assert!(parsed.is_mapping());

            // Must have cluster-specific values
            assert!(
                vars.contains(&format!("cluster_name: \"{}\"", cluster.cluster_name)),
                "{} missing cluster_name",
                cluster.cluster_name
            );
        }

        // Step 3: Verify cross-cluster uniqueness (cluster_ids must be unique)
        let cluster_ids: Vec<u32> = k8s_config
            .config
            .clusters
            .iter()
            .filter_map(|c| c.cilium.as_ref().map(|cil| cil.cluster_id))
            .collect();
        let mut unique_ids = cluster_ids.clone();
        unique_ids.sort();
        unique_ids.dedup();
        assert_eq!(
            cluster_ids.len(),
            unique_ids.len(),
            "cilium cluster_ids must be unique across clusters"
        );

        // Step 4: Verify OIDC only on sandbox (not tower)
        let tower = &k8s_config.config.clusters[0];
        let sandbox = &k8s_config.config.clusters[1];
        assert!(tower.oidc.is_none(), "tower should not have OIDC");
        assert!(
            sandbox.oidc.as_ref().unwrap().enabled,
            "sandbox should have OIDC enabled"
        );
        let sandbox_vars = generate_cluster_vars(sandbox, &k8s_config.config.common);
        assert!(sandbox_vars.contains("kube_oidc_auth: true"));
        let tower_vars = generate_cluster_vars(tower, &k8s_config.config.common);
        assert!(!tower_vars.contains("kube_oidc_auth"));
    }

    /// Edge case: A node with both control-plane AND worker roles must appear in both sections.
    #[test]
    fn test_inventory_dual_role_node_appears_in_both_sections() {
        let sdi = make_sdi_spec();
        // tower pool has tower-cp-0 with roles: [control-plane, worker]
        let cluster = make_cluster_def("tower", "tower");
        let ini = generate_inventory(&cluster, &sdi).unwrap();

        // tower-cp-0 must be in BOTH kube_control_plane AND kube_node
        let cp_section = ini.split("[kube_control_plane]").nth(1).unwrap();
        let cp_end = cp_section.find('[').unwrap_or(cp_section.len());
        let cp_content = &cp_section[..cp_end];
        assert!(
            cp_content.contains("tower-cp-0"),
            "dual-role node missing from kube_control_plane"
        );

        let node_section = ini.split("[kube_node]").nth(1).unwrap();
        let node_end = node_section.find('[').unwrap_or(node_section.len());
        let node_content = &node_section[..node_end];
        assert!(
            node_content.contains("tower-cp-0"),
            "dual-role node missing from kube_node"
        );
    }

    /// A-1: kube_api_anonymous_auth flow — kubespray_extra_vars must appear in generated YAML
    /// and the resulting YAML must be parseable with the correct value.
    #[test]
    fn test_cluster_vars_kube_api_anonymous_auth_flow() {
        let common = make_common();
        let mut cluster = make_cluster_def("tower", "tower");
        cluster.kubespray_extra_vars =
            Some(serde_yaml::from_str("kube_api_anonymous_auth: true").unwrap());

        let vars = generate_cluster_vars(&cluster, &common);

        // Must contain the key
        assert!(
            vars.contains("kube_api_anonymous_auth"),
            "kube_api_anonymous_auth missing from generated cluster-vars"
        );

        // Parse and verify the actual value
        let parsed: serde_yaml::Value = serde_yaml::from_str(&vars)
            .unwrap_or_else(|e| panic!("cluster-vars YAML invalid: {e}"));
        let anon_auth = parsed
            .get("kube_api_anonymous_auth")
            .expect("kube_api_anonymous_auth key not found in parsed YAML");
        assert_eq!(
            anon_auth.as_bool(),
            Some(true),
            "kube_api_anonymous_auth should be true"
        );
    }

    /// A-1 complementary: kubespray_extra_vars that duplicate core keys produce
    /// duplicate YAML keys — serde_yaml (strict mode) rejects this.
    /// This test documents that users must NOT put core keys in extra_vars.
    #[test]
    fn test_cluster_vars_extra_vars_duplicate_core_key_produces_invalid_yaml() {
        let common = make_common();
        let mut cluster = make_cluster_def("tower", "tower");
        // Attempt to override a core key via extra_vars
        cluster.kubespray_extra_vars =
            Some(serde_yaml::from_str("kube_version: \"9.99.0\"").unwrap());

        let vars = generate_cluster_vars(&cluster, &common);

        // Generated output contains duplicate kube_version — strict YAML parsers reject this
        assert!(
            vars.matches("kube_version").count() >= 2,
            "extra_vars with core key should produce duplicate key in output"
        );

        // serde_yaml strict mode rejects duplicate keys
        let result: Result<serde_yaml::Value, _> = serde_yaml::from_str(&vars);
        assert!(
            result.is_err(),
            "Duplicate core key in extra_vars should make YAML invalid (strict mode)"
        );
    }

    /// A-4: Cilium ClusterMesh cluster_id uniqueness across example configs.
    #[test]
    fn test_example_configs_cilium_cluster_ids_unique() {
        let k8s_content = include_str!("../../../config/k8s-clusters.yaml.example");
        let k8s: crate::models::cluster::K8sClustersConfig =
            serde_yaml::from_str(k8s_content).unwrap();

        let ids: Vec<u32> = k8s
            .config
            .clusters
            .iter()
            .filter_map(|c| c.cilium.as_ref().map(|cil| cil.cluster_id))
            .collect();

        let unique: std::collections::HashSet<u32> = ids.iter().copied().collect();
        assert_eq!(
            ids.len(),
            unique.len(),
            "Cilium cluster_ids in k8s-clusters.yaml.example must be unique. Found: {:?}",
            ids
        );

        // IDs must be in valid range (1-255 for ClusterMesh)
        for id in &ids {
            assert!(
                *id >= 1 && *id <= 255,
                "Cilium cluster_id {} out of valid range 1-255",
                id
            );
        }
    }

    /// A-2: Cross-config IP consistency — sdi-specs node IPs must not overlap with k8s-clusters CIDRs.
    #[test]
    fn test_example_configs_ip_no_overlap_between_node_and_service_cidrs() {
        let sdi_content = include_str!("../../../config/sdi-specs.yaml.example");
        let k8s_content = include_str!("../../../config/k8s-clusters.yaml.example");

        let sdi: SdiSpec = serde_yaml::from_str(sdi_content).unwrap();
        let k8s: crate::models::cluster::K8sClustersConfig =
            serde_yaml::from_str(k8s_content).unwrap();

        // Collect all node IPs from SDI spec
        let node_ips: Vec<String> = sdi
            .spec
            .sdi_pools
            .iter()
            .flat_map(|p| p.node_specs.iter().map(|n| n.ip.clone()))
            .collect();

        // Verify no node IP starts with a pod/service CIDR prefix
        for cluster in &k8s.config.clusters {
            let pod_prefix = cluster.network.pod_cidr.split('/').next().unwrap();
            let svc_prefix = cluster.network.service_cidr.split('/').next().unwrap();

            // Extract first two octets for rough overlap check
            let pod_base: Vec<&str> = pod_prefix.split('.').take(2).collect();
            let svc_base: Vec<&str> = svc_prefix.split('.').take(2).collect();

            for ip in &node_ips {
                let ip_base: Vec<&str> = ip.split('.').take(2).collect();
                assert_ne!(
                    ip_base, pod_base,
                    "Node IP {} overlaps with pod CIDR {} of cluster {}",
                    ip, cluster.network.pod_cidr, cluster.cluster_name
                );
                assert_ne!(
                    ip_base, svc_base,
                    "Node IP {} overlaps with service CIDR {} of cluster {}",
                    ip, cluster.network.service_cidr, cluster.cluster_name
                );
            }
        }
    }

    /// A-3: GitOps sync-wave ordering — verify generators reference valid sync-wave values.
    #[test]
    fn test_gitops_generator_apps_have_valid_sync_wave_order() {
        let generators = [
            include_str!("../../../gitops/generators/tower/common-generator.yaml"),
            include_str!("../../../gitops/generators/tower/tower-generator.yaml"),
            include_str!("../../../gitops/generators/sandbox/common-generator.yaml"),
            include_str!("../../../gitops/generators/sandbox/sandbox-generator.yaml"),
        ];

        let mut sync_waves: Vec<(String, i32)> = Vec::new();
        for content in &generators {
            // Parse sync-wave annotations from generator elements
            for line in content.lines() {
                if line.contains("sync-wave") {
                    // Extract the sync-wave value (format: argocd.argoproj.io/sync-wave: "N")
                    if let Some(val) = line.split('"').nth(1).or_else(|| line.split('\'').nth(1)) {
                        if let Ok(wave) = val.parse::<i32>() {
                            sync_waves.push((line.trim().to_string(), wave));
                        }
                    }
                }
            }
        }

        // All sync-wave values must be in valid range (0-10)
        for (context, wave) in &sync_waves {
            assert!(
                *wave >= 0 && *wave <= 10,
                "Sync-wave {} out of expected range 0-10: {}",
                wave,
                context
            );
        }
    }

    /// A-5: Enhanced pipeline dry-run — verify every generated cluster-vars
    /// contains ALL addon disablements AND cluster-specific settings.
    #[test]
    fn test_full_pipeline_dryrun_addon_disablement_all_clusters() {
        let k8s_yaml = r#"
config:
  common:
    kubernetes_version: "1.33.1"
    kubespray_version: "v2.30.0"
    container_runtime: "containerd"
    cni: "cilium"
    cilium_version: "1.17.5"
    kube_proxy_remove: true
    cgroup_driver: "systemd"
    helm_enabled: true
    kube_apiserver_admission_plugins: [NodeRestriction]
    firewalld_enabled: false
    kube_vip_enabled: false
    kubeconfig_localhost: true
    kubectl_localhost: true
    enable_nodelocaldns: true
    kube_network_node_prefix: 24
    ntp_enabled: true
  clusters:
    - cluster_name: "tower"
      cluster_sdi_resource_pool: "tower"
      cluster_role: "management"
      network:
        pod_cidr: "10.244.0.0/20"
        service_cidr: "10.96.0.0/20"
        dns_domain: "tower.local"
      cilium:
        cluster_id: 1
        cluster_name: "tower"
      kubespray_extra_vars:
        kube_api_anonymous_auth: true
    - cluster_name: "sandbox"
      cluster_sdi_resource_pool: "sandbox"
      cluster_role: "workload"
      network:
        pod_cidr: "10.233.0.0/17"
        service_cidr: "10.233.128.0/18"
        dns_domain: "sandbox.local"
      cilium:
        cluster_id: 2
        cluster_name: "sandbox"
      kubespray_extra_vars:
        kube_api_anonymous_auth: true
"#;

        let k8s_config: crate::models::cluster::K8sClustersConfig =
            serde_yaml::from_str(k8s_yaml).unwrap();

        let disabled_addons = [
            "cert_manager_enabled: false",
            "argocd_enabled: false",
            "metallb_enabled: false",
            "ingress_nginx_enabled: false",
            "local_path_provisioner_enabled: false",
            "node_feature_discovery_enabled: false",
            "metrics_server_enabled: false",
            "registry_enabled: false",
        ];

        for cluster in &k8s_config.config.clusters {
            let vars = generate_cluster_vars(cluster, &k8s_config.config.common);

            // Every cluster must have ALL addon disablements
            for addon in &disabled_addons {
                assert!(
                    vars.contains(addon),
                    "Cluster '{}' missing addon disablement: {}",
                    cluster.cluster_name,
                    addon
                );
            }

            // Every cluster with kubespray_extra_vars must have kube_api_anonymous_auth
            if cluster.kubespray_extra_vars.is_some() {
                assert!(
                    vars.contains("kube_api_anonymous_auth"),
                    "Cluster '{}' missing kube_api_anonymous_auth from extra_vars",
                    cluster.cluster_name
                );
            }

            // Generated YAML must be valid
            let parsed: serde_yaml::Value = serde_yaml::from_str(&vars).unwrap_or_else(|e| {
                panic!("Cluster '{}' vars invalid YAML: {e}", cluster.cluster_name)
            });
            assert!(parsed.is_mapping());
        }
    }

    /// Edge case: kubespray_extra_vars with nested YAML (systemReserved) must merge correctly.
    #[test]
    fn test_cluster_vars_nested_extra_vars_merge() {
        let common = make_common();
        let mut cluster = make_cluster_def("sandbox", "sandbox");
        cluster.kubespray_extra_vars = Some(
            serde_yaml::from_str(
                r#"
kube_api_anonymous_auth: true
kubelet_config_extra_args:
  systemReserved:
    cpu: "200m"
    memory: "512Mi"
  kubeReserved:
    cpu: "200m"
    memory: "512Mi"
supplementary_addresses_in_ssl_keys:
  - "100.64.0.1"
"#,
            )
            .unwrap(),
        );
        let vars = generate_cluster_vars(&cluster, &common);

        // Must be valid YAML
        let parsed: serde_yaml::Value = serde_yaml::from_str(&vars)
            .unwrap_or_else(|e| panic!("nested extra_vars broke YAML: {e}\n---\n{vars}"));
        assert!(parsed.is_mapping());

        // Nested values must be present (serde_yaml may omit quotes for simple strings)
        assert!(vars.contains("systemReserved:"), "missing systemReserved");
        assert!(
            vars.contains("cpu:") && vars.contains("200m"),
            "missing cpu reservation"
        );
        assert!(
            vars.contains("100.64.0.1"),
            "missing supplementary SSL address"
        );
    }

    /// etcd_deployment_type must be explicitly set for production clusters.
    /// Default: "host" (recommended for production — avoids container orchestration overhead)
    #[test]
    fn test_cluster_vars_etcd_deployment_type() {
        let common = make_common();
        let cluster = make_cluster_def("tower", "tower");
        let vars = generate_cluster_vars(&cluster, &common);

        assert!(
            vars.contains("etcd_deployment_type:"),
            "missing etcd_deployment_type — required for production (DataX uses 'host')"
        );
        assert!(
            vars.contains("etcd_deployment_type: host"),
            "etcd_deployment_type should default to 'host'"
        );
    }

    /// dns_mode must be explicitly set for production clusters.
    /// Default: "coredns" (production standard for Kubernetes DNS resolution)
    #[test]
    fn test_cluster_vars_dns_mode() {
        let common = make_common();
        let cluster = make_cluster_def("tower", "tower");
        let vars = generate_cluster_vars(&cluster, &common);

        assert!(
            vars.contains("dns_mode:"),
            "missing dns_mode — required for production (DataX uses 'coredns')"
        );
        assert!(
            vars.contains("dns_mode: coredns"),
            "dns_mode should default to 'coredns'"
        );
    }

    /// The required_keys list must include etcd_deployment_type and dns_mode
    #[test]
    fn test_cluster_vars_required_keys_include_datax_production_settings() {
        let common = make_common();
        let cluster = make_cluster_def("tower", "tower");
        let vars = generate_cluster_vars(&cluster, &common);
        let parsed: serde_yaml::Mapping = serde_yaml::from_str(&vars).unwrap();

        let production_keys = ["etcd_deployment_type", "dns_mode"];

        for key in &production_keys {
            assert!(
                parsed.contains_key(serde_yaml::Value::String(key.to_string())),
                "missing production-required kubespray key: {key}"
            );
        }
    }

    #[test]
    fn test_generate_inventory_baremetal_single_node_dual_role() {
        // Single bare-metal node acting as both control-plane and worker
        let cluster = ClusterDef {
            cluster_name: "mini".to_string(),
            cluster_mode: crate::models::cluster::ClusterMode::Baremetal,
            cluster_sdi_resource_pool: String::new(),
            baremetal_nodes: vec![crate::models::cluster::BaremetalNode {
                node_name: "node-0".to_string(),
                ip: "10.0.0.1".to_string(),
                roles: vec![
                    "control-plane".to_string(),
                    "etcd".to_string(),
                    "worker".to_string(),
                ],
            }],
            cluster_role: "management".to_string(),
            network: ClusterNetwork {
                pod_cidr: "10.244.0.0/20".to_string(),
                service_cidr: "10.96.0.0/20".to_string(),
                dns_domain: "mini.local".to_string(),
                native_routing_cidr: None,
            },
            cilium: None,
            oidc: None,
            kubespray_extra_vars: None,
            ssh_user: None,
        };
        let ini = generate_inventory_baremetal(&cluster).unwrap();

        // Node appears in all three role sections
        assert!(ini.contains("[kube_control_plane]\nnode-0"));
        assert!(ini.contains("[etcd]\nnode-0"));
        assert!(ini.contains("[kube_node]\nnode-0"));
        // Only one entry in [all]
        assert_eq!(ini.matches("ansible_host=10.0.0.1").count(), 1);
    }

    #[test]
    fn test_generate_inventory_baremetal_no_control_plane_rejected() {
        // Workers-only cluster should be rejected (Kubespray requires control-plane)
        let cluster = ClusterDef {
            cluster_name: "workers-only".to_string(),
            cluster_mode: crate::models::cluster::ClusterMode::Baremetal,
            cluster_sdi_resource_pool: String::new(),
            baremetal_nodes: vec![
                crate::models::cluster::BaremetalNode {
                    node_name: "w-0".to_string(),
                    ip: "10.0.0.1".to_string(),
                    roles: vec!["worker".to_string()],
                },
                crate::models::cluster::BaremetalNode {
                    node_name: "w-1".to_string(),
                    ip: "10.0.0.2".to_string(),
                    roles: vec!["worker".to_string()],
                },
            ],
            cluster_role: "workload".to_string(),
            network: ClusterNetwork {
                pod_cidr: "10.233.0.0/17".to_string(),
                service_cidr: "10.233.128.0/18".to_string(),
                dns_domain: "workers.local".to_string(),
                native_routing_cidr: None,
            },
            cilium: None,
            oidc: None,
            kubespray_extra_vars: None,
            ssh_user: None,
        };
        let result = generate_inventory_baremetal(&cluster);
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("control-plane"));
    }
}
