server:
  service:
    type: ClusterIP
  replicas: 1
controller:
  replicas: 1
repoServer:
  replicas: 1
redis:
  ha:
    enabled: false
persistence:
  enabled: true
global:
  domain: cd.jinwang.dev
configs:
  params:
    server.insecure: "true"
  cm:
    kustomize.buildOptions: --enable-helm
